easy_admin:
  site_name: 'On-Demand Admin'

  list:
    batch_actions: ['delete']
    actions:
      - { name: 'edit', icon: 'pencil', label: false }
      - { name: 'delete', icon: 'trash', label: false }

  user:
    display_name: true
    display_avatar: false
    name_property_path: 'fullName'

  entities:
    User:
      class: App\Entity\User
      list:
        fields:
          - id
          - firstName
          - lastName
          - email
          - roles
          - createdAt
          - updatedAt
      form:
        fields:
          - firstName
          - lastName
          - email
          - password
          - roles
          - { property: addresses, type_options: { required: false }}
          - { property: orders, type_options: { required: false }}
    Product:
      class: App\Entity\Product
      form:
        form_options: { validation_groups: false }
    Category:
      class: App\Entity\Category
    Address:
      class: App\Entity\Address
    Order:
      class: App\Entity\Order
      list:
        actions:
          - { name: 'changeState', template: 'admin/actions/changeState.html.twig' }
      form:
        fields:
          - firstName
          - lastNam
          - phon
          - use
          - addres
          - { property: 'orderProducts', type_options: { required: false }}
        form_options: { validation_groups: false }
    OrderProduct:
      class: App\Entity\OrderProduct

  design:
    brand_color: '#eb4a35'
    assets:
#      favicon: '/assets/backend/favicon.png'
      css:
          - 'bundles/easyadmin/bootstrap-all.css'
      js:
          - 'bundles/easyadmin/bootstrap-all.js'

    menu:
#      - label: 'Users'
#        children: ['User']
      - { entity: 'User', icon: 'user' }
      - Address
      - Category
      - Product
      - Order
      - { label: 'Orders Products', entity: 'OrderProduct' }
      - { label: 'Logout', url: '/logout', icon: 'door-open' }
