index:
#    controller: App\Controller\DefaultController::index
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /admin
        permanent: true

api_login_check:
    path: /api/login_check
    methods: ['POST']
